PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
ASK {
  obo:BFO_0000001 rdfs:subClassOf* ?class .
  FILTER NOT EXISTS {
    ?subclass rdfs:subClassOf ?class .
    FILTER (?subclass != obo:BFO_0000001)
    FILTER (?subclass != obo:UBERON_0001062)
    FILTER (?subclass != obo:BFO_0000016)
    FILTER (?subclass != obo:IAO_0000030)
    FILTER (?subclass != obo:BFO_0000040)
    FILTER (?subclass != obo:BFO_0000015)
    FILTER (?subclass != obo:BFO_0000019)
  }
}
