PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?class WHERE {
  ?class a owl:Class .
  FILTER(ISIRI(?class))
  FILTER NOT EXISTS {
    ?class rdfs:subClassOf ?superclass .
  }
  FILTER (?class != obo:BFO_0000001)
}
