name: ROBOT enanomapper-dev build test
on:
  workflow_dispatch:
    
  workflow_run:
    workflows: ["Build slims"]
    types:
      - completed
    

jobs:
    robot-workflows:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: retrieve urls from config file
          run: |
            config_file="config.yaml"
            robot_jar=""
            robot=""
            slimmer=""
          
            while IFS=":" read -r key value; do
              key=$(echo "$key" | tr -d '[:space:]')
          
              case "$key" in
                robot-jar)
                  robot_jar=$(echo "$value" | tr -d '[:space:]')
                  ;;
                robot-wrapper)
                  robot=$(echo "$value" | tr -d '[:space:]')
                  ;;
              esac
            done < "$config_file"
            echo 'robot='${robot}'' >> $GITHUB_ENV
            echo 'robot_jar='${robot_jar}'' >> $GITHUB_ENV
            echo ROBOT JAR: $robot_jar
            echo ROBOT WRAPPER: $robot
        - name: get robot
          run: |
            ls
            wget ${{ env.robot }}
            wget ${{ env.robot_jar }}
            mkdir -p robot-report
    
        - name: merge
          run: | 
            sh robot merge -i enanomapper-dev.owl -o enanomapper-dev-full.owl
            sh robot merge -i enanomapper.owl -o enanomapper-full.owl
            
  # Upload owl artifacts
        - name: 'Upload enanomapper* artifacts'
          uses: actions/upload-artifact@v3
          with:
            name: enanomapper-files
            path: enanomapper*
  
        - name: report
          run: sh robot report --fail-on none -i enanomapper-dev-full.owl -o robot-report/report.tsv
        - name: diff
          run: |
            sh robot diff --left enanomapper-full.owl --right enanomapper-dev-full.owl --output robot-report/diff.txt
        - name: reason
          run: |
            sh robot reason --reasoner ELK --input enanomapper-dev-full.owl -D debug-dev.owl
            sh robot reason --reasoner ELK --input enanomapper-full.owl -D debug.owl
            FILE=debug*
              if test -f "$FILE"; then
                echo $(DEBUG=True) >> $GITHUB_ENV  
              fi

        - name: rm temp owl files
          run: |
            rm enanomapper-full.owl
            rm enanomapper-dev-full.owl
            
  # Upload debug artifacts
        - name: 'Upload enanomapper* artifacts'
          uses: actions/upload-artifact@v3
          if: ${{ env.DEBUG }}
          with:
            name: debug-files
            path: debug*
            
        - name: 'Upload report'
          uses: actions/upload-artifact@v3
          with:
            name: report
            path: ./robot-report/* 
        - name: Create issue about failure
          if: failure()
          uses: JasonEtco/create-an-issue@v2.5.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            filename: .github/action-issue-template.md
            
