name: Pre-release tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3

    - name: Install dependencies
      run: pip install -r scripts/src/tests/prerelease_tests/requirements.txt

    - name: Run tests
      run: python -m unittest discover scripts/src/tests/prerelease_tests/
    - name: Create issue about failure
      if: failure()
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/action-issue-template.md
        update_existing: true
