name: workflow qc eNanoMapper
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v2
        - name: get robot
          run: |
            ls
            wget https://raw.githubusercontent.com/ontodev/robot/master/bin/robot
            wget https://github.com/ontodev/robot/releases/download/v1.9.0/robot.jar
            chmod 777 robo*
    
        - name: merge
          run: sh robot merge -i enanomapper.owl -o enanomapper.owl
        - name: report
          run: sh robot report -i enanomapper.owl -o robot-report/report.tsv
  # Commit and push
        - name: Commit OWL files
          run: |
            git add enanomapper-full.owl
            git add ./report/*
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Actions - QC" ./report/* enanomapper-full.owl
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${ secretsGITHUB_TOKEN }
            branch: ${ github.ref }   
  