name: update repository
permissions: write-all
on:
  push:
    branches:
    - main
    - master
jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
       token: ${{ secrets.PAT }} 
    - name: update according to new yaml settings
      run:  |
        cd scripts/src/build-workflow 
        python makeBuild.py
        python makeROBOT.py
        cd ../../../
    - name: commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/workflows/*.yml
        git commit -m "Updated workflow" .github/workflows/*.yml
        git push
