name: update repository
on:
  push:
    branches:
    - main
    - master
jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: update according to new yaml settings
      run:  |
        cd scripts/src/build-workflow 
        python makeBuild.py
        python makeROBOT.py
        cd ../../../
    - name: commit and push changes
      run: |
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/workflows/*.yml
        git commit -m "Updated repository" .github/workflows/*.yml
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.WORKFLOWS }}
        branch: ${{ github.ref }}   
